sudo: false
language: elixir
elixir:
  - 1.6
otp_release:
  - 20.2
cache:
  directories:
    - _build
    - deps
env:
  global:
    - HEX_USERNAME=bryanjos
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  # https://docs.travis-ci.com/user/deployment/script/
  # > `script` must be a scalar pointing to an executable file or command.
  provider: script
  # http://yaml.org/spec/1.2/spec.html#id2779048
  # `>-` indicates the line folding.
  script: >-
    mix deps.get &&
    mix hex.config username "$HEX_USERNAME" &&
    (mix hex.config encrypted_key "$HEX_ENCRYPTED_KEY" > /dev/null 2>&1) &&
    (echo "$HEX_PASSPHRASE" | mix hex.publish --no-confirm) &&
    mix clean &&
    mix deps.clean --all
  on:
    tags: true
