sudo: false
language: elixir
elixir:
  - 1.6
otp_release:
  - 20.2
cache:
  directories:
    - _build
    - deps
env:
  global:
    - HEX_USERNAME=bryanjos
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
script:
  - MIX_ENV=test mix coveralls.travis
before_deploy:
  - mix compile
deploy:
  skip_cleanup: true
  provider: script
  script: mix hex.publish --yes
  on:
    tags: true
